--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ArabSkills-Official/StringLib
build-by-default: true
branches:
- master
projects:
  StringLib:
    path: ""
    model: virion
    type: library
...
